Increment3
jestenok/metric-collector pull request #3
Opened 2022-09-06 18:54 UTC by jestenok

2022-09-07 17:22 UTC, tmvrus requested changes
пожалуйста удалите закомментированый код, не засоряйте свой проект
и наведите порядок с content-type: у вас где-то c.JSON, где-то c.String а где-то c.String + json

2022-09-07 17:22 UTC, tmvrus commented on cmd/server/main.go
> +	r.POST("/update/:metricType/", handlers.NotFoundHandler)
добавлять эти хендлеры избыточно, gin по умолчанию вернет "404 page not found" если роут не известен
если вам действительно по какой-то причине нужен кастомный обработчик, то воспользуйтесь стандарными средствами gin
```
r := gin.New()
r.NoRoute(customHandlerForNotFound)
```

2022-09-07 17:22 UTC, tmvrus commented on internal/handlers/update.go
> +//}
если этот код не нужен, если следует удалить что бы не засорять проект

2022-09-07 17:22 UTC, tmvrus commented on internal/handlers/value.go
> +	c.Header("Content-Type", "application/json")
в начале хендлера ставится "Content-Type", "application/json"
но в случае, если метрика не найдена,  возвращается обычная строка, с точки зрения протокола - это ошибка, нужно что бы ответ соответствовал заголовку

2022-09-07 17:22 UTC, tmvrus commented on internal/handlers/value.go
> +	ok := false
вот эти значения можно не объявлять если воспользоваться синтаксисом ':='
```
value, ok := AgentMetrics[name]
if !ok {
// return not found
}
// return value
```

2022-09-07 17:22 UTC, tmvrus commented on internal/collector/metric.go
> +	case "counter":
эти строковое значения используются больше чем в одном месте, их лучше сделать константами

2022-09-07 17:22 UTC, tmvrus commented on internal/collector/metric.go
> +			return nil, ErrParseValue
`ErrParseValue` малоинформативна и говорит только о том, что что-то не получилось распарсить, рекомендую вам давать боле информативные сообщения об ошибках, например
```
return fmt.Errorf("failed to parse float value %q, error: %w", value, err)
```
таким образом при отладке вы сразу поймете что за значение и с какой ошибкой не распарсилось

2022-09-07 17:22 UTC, tmvrus commented on internal/collector/metric.go
> +			c[name] = existM.(Counter) + m.(Counter)
такое приведение типов - это потенциальная паника, старайтесь их избегать

2022-09-07 19:46 UTC, jestenok commented on cmd/server/main.go
> +	r.POST("/update/:metricType/", handlers.NotFoundHandler)
Автотесты ругаются при их отсутствии.
За подсказку с ноуроутером спасибо

2022-09-08 00:16 UTC, jestenok commented
Исправил все, кроме избыточных хендлеров 
без них автотесты не проходят
при запросе /update/counter или /update/counter/name
постман выдает 404 (как и требуется), а у автотестов 307 (редирект)
В чем может быть дело?

2022-09-08 11:43 UTC, jestenok commented
Добавил параметр RedirectTrailingSlash  и редирект перестал срабатывать

2022-09-08 19:59 UTC, tmvrus approved these changes

2022-09-08 19:59 UTC, tmvrus commented on internal/collector/metric.go
> +var counterType = "counter"
эти значения следовало бы сделать константами

2022-09-08 19:59 UTC, tmvrus commented on internal/handlers/error.go
> +	c.String(404, "404 page not found")
в пакете http есть специальный константы для статусов http.StatusXXX их использование существенно повышает читаемость кода

2022-09-08 19:59 UTC, tmvrus commented on internal/collector/metric.go
> +}
Очень интересное решение.

2022-09-08 19:59 UTC, tmvrus commented on internal/handlers/update.go
> +var AgentMetrics = make(collector.CollectedMetrics)
Использование глобальной переменной для хранения метрик не является критичным на данный момент, но в следующих итерациях создаст вам проблемы. Рекомендую пересмотреть этот подход.

2022-09-13 23:29 UTC, merged